version: '3'
services:
  rabbit:
    build:
      context: ./dockerRabbitmq
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=iot_vdc
      - RABBITMQ_DEFAULT_PASS=iotvdc_2024
